# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and engines loaded when an Asset is loaded. Since std VFX config
  template has a file system structure which is centered around pipeline steps, this
  environment is largely empty. Most of the work takes place on a level in the file
  system where both an asset and a pipeline step is available - e.g Asset Hero, modeling,
  so all apps for loading, publishing etc. are located in the asset_step environment.
  This environment mostly contains utility apps and the tank work files app, which
  lets you choose a task to work on and load associated content into an application.

#################################################################################################
# include common files
includes:
# launchers for launching DCCs such as Maya, Nuke etc.
- ./includes/app_launchers.yml
# common app configurations that are reused across environments
- ./includes/common_apps.yml

#################################################################################################
# define all the items that should appear in this environment



engines:
  #
  # -------------------------------------------------
  # 3dsmax plus
  # -------------------------------------------------
  tk-3dsmaxplus:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    compatibility_dialog_min_version: 2017
    debug_logging: false
    location:
      version: v0.5.1
      type: app_store
      name: tk-3dsmaxplus
    menu_favourites: []
  #
  # -------------------------------------------------
  # Houdini
  # -------------------------------------------------
  tk-houdini:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    location:
      version: v1.3.0
      type: app_store
      name: tk-houdini
    enable_sg_shelf: true
    debug_logging: false
    enable_sg_menu: true
    menu_favourites: []
  #
  # -------------------------------------------------
  # Mari
  # -------------------------------------------------
  tk-mari:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_filter_publishes: default
        hook_filter_work_files: default
        hook_scene_operation: default
        launch_at_startup: false
        launch_change_work_area_at_startup: false
        location:
          version: v0.7.4
          type: app_store
          name: tk-multi-workfiles
        saveas_default_name: scene
        saveas_prefer_version_up: false
        sg_entity_type_extra_display_fields: {}
        sg_entity_type_filters: {}
        sg_entity_types: [Asset]
        sg_task_filters: []
        task_extra_display_fields: []
        template_publish:
        template_publish_area:
        template_work:
        template_work_area:
        version_compare_ignore_fields: []
    compatibility_dialog_min_version: 2
    debug_logging: false
    location:
      version: v1.2.0
      type: app_store
      name: tk-mari
  #
  # -------------------------------------------------
  # Maya
  # -------------------------------------------------
  tk-maya:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel:
        action_mappings:
          PublishedFile:
          - actions: [reference, import]
            filters: {published_file_type: Maya Scene, Alembic}
          - actions: [texture_node]
            filters: {published_file_type: Rendered Image}
          - actions: [texture_node]
            filters: {published_file_type: Photoshop Image}
          - actions: [udim_texture_node]
            filters: {published_file_type: UDIM Image}
          Task:
          - actions: [assign_task, task_to_ip]
            filters: {}
        actions_hook: '{self}/general_actions.py:{self}/tk-maya_actions.py'
        location:
          version: v1.4.9
          type: app_store
          name: tk-multi-shotgunpanel
        shotgun_fields_hook: '{self}/shotgun_fields.py'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2:
        allow_task_creation: false
        create_new_task_hook: '{self}/create_new_task.py'
        custom_actions_hook: '{self}/custom_actions.py'
        entities:
        - caption: Assets
          entity_type: Task
          filters:
          - [entity, type_is, Asset]
          hierarchy: [entity.Asset.sg_asset_type, entity, content]
        - caption: Shots
          entity_type: Task
          filters:
          - [entity, type_is, Shot]
          hierarchy: [entity.Shot.sg_sequence, entity, content]
        file_extensions: []
        hook_copy_file: '{self}/copy_file.py'
        hook_filter_publishes: default
        hook_filter_work_files: default
        hook_scene_operation: '{config}/scene_operation_tk-maya.py'
        launch_at_startup: true
        location:
          version: v0.9.9
          type: app_store
          name: tk-multi-workfiles2
        my_tasks_extra_display_fields: []
        saveas_default_name: scene
        saveas_prefer_version_up: false
        show_my_tasks: false
        template_publish: maya_asset_work
        template_publish_area: asset_publish_area_maya
        template_work: maya_asset_work
        template_work_area: asset_root
        version_compare_ignore_fields: []
      tk-multi-loader2:
        action_mappings:
          Maya Scene: [reference, import]
          Photoshop Image: [texture_node]
          Rendered Image: [texture_node]
          Alembic Cache: [import]
        actions_hook: '{self}/tk-maya_actions.py'
        download_thumbnails: true
        entities:
        - caption: Assets
          entity_type: Asset
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_asset_type, code]
        - caption: Shots
          entity_type: Shot
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_sequence, code]
        - caption: My Tasks
          entity_type: Task
          filters:
          - [task_assignees, is, '{context.user}']
          - [project, is, '{context.project}']
          hierarchy: [entity, content]
        filter_publishes_hook: '{self}/filter_publishes.py'
        location:
          version: v1.18.1
          type: app_store
          name: tk-multi-loader2
        menu_name: Load
        publish_filters: []
        title_name: Loader

      tk-multi-publish:
        location:
          version: v0.10.9
          type: app_store
          name: tk-multi-publish
        allow_taskless_publishes: true
        display_name: Publish
        expand_single_items: false
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: '{config}/primary_publish.py'
        hook_scan_scene: '{config}/scan_scene_tk-maya.py'
        hook_secondary_pre_publish: '{config}/secondary_pre_publish_tk-maya.py'
        hook_secondary_publish: '{config}/secondary_publish_tk-maya.py'
        hook_thumbnail: default
        primary_description: Publish and version up the current Maya scene
        primary_display_name: Maya Publish
        primary_icon: icons/publish_maya_main.png
        primary_publish_template: maya_asset_publish
        primary_scene_item_type: work_file
        primary_tank_type: Maya Scene
        template_work: maya_asset_work
        secondary_outputs:
        - description: 'Publish a camera'
          display_group: Cameras
          display_name: Camera
          icon: 'icons/camera.png'
          name: camera
          publish_template: maya_asset_camera
          required: false
          scene_item_type: camera
          selected: true
          publish_group: false
          group_name: default
          tank_type: 'Camera'
        - description: 'Publish Alembic Cache data for the model'
          display_group: Caches
          display_name: Alembic Cache
          icon: 'icons/alembic_output.png'
          name: alembic_cache
          publish_template: maya_asset_mesh_alembic_cache
          required: false
          scene_item_type: mesh_group
          selected: false
          tank_type: 'Alembic Cache'

    compatibility_dialog_min_version: 2015
    debug_logging: false
    location:
      version: v0.9.1
      type: app_store
      name: tk-maya
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    template_project: asset_root
    use_sgtk_as_menu_name: false

  #
  # -------------------------------------------------
  # Motionbuilder
  # -------------------------------------------------
  tk-motionbuilder:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    debug_logging: false
    location:
      version: v0.4.0
      type: app_store
      name: tk-motionbuilder
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    use_sgtk_as_menu_name: false

  #
  # -------------------------------------------------
  # Nuke
  # -------------------------------------------------
  tk-nuke:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
      tk-nuke-writenode:
        location:
          version: v1.2.0
          type: app_store
          name: tk-nuke-writenode
    compatibility_dialog_min_version: 10
    debug_logging: false
    favourite_directories: []
    location:
      version: v0.9.4
      type: app_store
      name: tk-nuke
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    project_favourite_name: Shotgun Current Project
    use_sgtk_as_menu_name: false
    bin_context_menu: []
    spreadsheet_context_menu: []
    timeline_context_menu: []
  #
  # -------------------------------------------------
  # Photoshop CC
  # -------------------------------------------------
  tk-photoshopcc:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    shelf_favorites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    - {app_instance: tk-multi-workfiles2, name: File Save...}
    debug_logging: false
    location:
      version: v1.2.1
      type: app_store
      name: tk-photoshopcc
  #
  # -------------------------------------------------
  # Shell
  # -------------------------------------------------
  tk-shell:
    apps:
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchhoudini: '@launch_houdini'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchmotionbuilder: '@launch_motionbuilder'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchphotoshopcc: '@launch_photoshopcc'
      tk-multi-launchsoftimage: '@launch_softimage'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-shotgun-launchmari: '@launch_mari'
    location:
      version: v0.6.0
      type: app_store
      name: tk-shell
  #
  # -------------------------------------------------
  # Softimage
  # -------------------------------------------------
  tk-softimage:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    debug_logging: false
    location:
      version: v0.3.4
      type: app_store
      name: tk-softimage
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    template_project:
#
###############################################################################
#
# Framework includes.
#
# Frameworks are libraries that are shared between apps and that contain
# common functionality for building UIs and communicating with Shotgun.
# Frameworks are automatically installed when apps are installed and udpated.
#
frameworks:
  tk-framework-softimageqt_v1.0.1:
    location:
      name: tk-framework-softimageqt
      type: app_store
      version: v1.0.1
