# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# description: Apps and engines loaded when a Shot is loaded. Since std VFX config template
#  has a file system structure which is centered around pipeline steps, this environment
#  is largely empty. Most of the work takes place on a level in the file system where
#  both a shot and a pipeline step is available - e.g Shot ABC, modeling, so all apps
#  for loading, publishing etc. are located in the shot_step environment. This environment
#  mostly contains utility apps and the tank work files app, which lets you choose
#  a task to work on and load associated content into an application.

description: Apps and Engines related to Shot based work.

#################################################################################################
# include common files

includes:
# launchers for launching DCCs such as Maya, Nuke etc.
- ./includes/app_launchers.yml
# common app configurations that are reused across environments
- ./includes/common_apps.yml

#################################################################################################
# define all the items that should appear in this environment


engines:
  #
  # -------------------------------------------------
  # 3dsmax plus
  # -------------------------------------------------
  tk-3dsmaxplus:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    compatibility_dialog_min_version: 2017
    debug_logging: false
    location:
      version: v0.4.1
      type: app_store
      name: tk-3dsmaxplus
    menu_favourites: []
  #
  # -------------------------------------------------
  # Houdini
  # -------------------------------------------------
  tk-houdini:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    location:
      version: v1.2.7
      type: app_store
      name: tk-houdini
    enable_sg_shelf: true
    debug_logging: false
    enable_sg_menu: true
    menu_favourites: []
  #
  # -------------------------------------------------
  # maya
  # -------------------------------------------------
  tk-maya:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2-launch-at-startup'
    compatibility_dialog_min_version: 2015
    debug_logging: false
    location:
      version: v0.8.3
      type: app_store
      name: tk-maya
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    template_project:
    use_sgtk_as_menu_name: false

  #
  # -------------------------------------------------
  # motionbuilder
  # -------------------------------------------------
  tk-motionbuilder:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    debug_logging: false
    location:
      version: v0.3.1
      type: app_store
      name: tk-motionbuilder
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    use_sgtk_as_menu_name: false

  #
  # -------------------------------------------------
  # nuke
  # -------------------------------------------------
  tk-nuke:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-nuke-quickdailies:
        location:
          version: v0.3.5
          type: app_store
          name: tk-nuke-quickdailies
        movie_template: shot_quicktime_quick
        post_hooks: [snapshot_history_post_quickdaily]
        sg_version_name_template: nuke_quick_shot_version_name
        width: 1920
        height: 1080
        upload_movie: true
        codec_settings_hook: '{self}/codec_settings.py'
        current_scene_template: nuke_shot_work
      tk-nuke-writenode:
        location:
          version: v1.2.0
          type: app_store
          name: tk-nuke-writenode
        template_script_work: nuke_shot_work
        write_nodes:
        - file_type: exr
          name: Mono Exr, 32 bit
          proxy_publish_template: null
          proxy_render_template: null
          publish_template: nuke_shot_render_pub_mono_exr
          render_template: nuke_shot_render_mono_exr
          settings:
            datatype: 32 bit float
          tank_type: Rendered Image
          tile_color: []
          promote_write_knobs: []
        - file_type: dpx
          name: Mono Dpx
          proxy_publish_template: null
          proxy_render_template: null
          publish_template: nuke_shot_render_pub_mono_dpx
          render_template: nuke_shot_render_mono_dpx
          settings:
            datatype: 16 bit
          tank_type: Rendered Image
          tile_color: []
          promote_write_knobs: []
      tk-multi-publish:
        location:
          version: v0.10.7
          type: app_store
          name: tk-multi-publish
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location:
          version: v0.7.3
          type: app_store
          name: tk-multi-snapshot
        template_snapshot: nuke_shot_snapshot
        template_work: nuke_shot_work
      tk-multi-loader2:
        location:
          version: v1.18.0
          type: app_store
          name: tk-multi-loader2
      tk-multi-workfiles2:
        location:
          version: v0.9.7
          type: app_store
          name: tk-multi-workfiles2
        template_publish: nuke_shot_publish
        template_publish_area: shot_publish_area_nuke
        template_work: nuke_shot_work
        template_work_area: shot_work_area_nuke
        launch_at_startup: true
        show_my_tasks: true
        saveas_default_name: ShotNumber
        file_extensions: []
        saveas_prefer_version_up: false
        hook_filter_work_files: '{self}/filter_work_files.py'
        create_new_task_hook: '{self}/create_new_task.py'
        hook_copy_file: '{self}/copy_file.py'
        allow_task_creation: False

        entities:
        - caption: Assets
          entity_type: Task
          filters:
          - [entity, type_is, Asset]
          hierarchy: [entity.Asset.sg_asset_type, entity, step, content]
        - caption: Shots
          entity_type: Task
          filters:
          - [entity, type_is, Shot]
          hierarchy: [entity.Shot, entity, project, content]
          my_tasks_extra_display_fields: []
          version_compare_ignore_fields: []
          hook_scene_operation: '{self}/scene_operation_{engine_name}.py'
          hook_filter_publishes: '{self}/filter_publishes.py'
          custom_actions_hook: '{self}/custom_actions.py'
          auto_expand tree: False



    compatibility_dialog_min_version: 10
    debug_logging: false
    favourite_directories: []
    location:
      version: v0.8.5
      type: app_store
      name: tk-nuke
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    project_favourite_name: Shotgun Current Project
    use_sgtk_as_menu_name: false
    bin_context_menu: []
    spreadsheet_context_menu: []
    timeline_context_menu: []
  #
  # -------------------------------------------------
  # Photoshop CC
  # -------------------------------------------------
  tk-photoshopcc:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    shelf_favorites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    - {app_instance: tk-multi-workfiles2, name: File Save...}
    debug_logging: false
    location:
      version: v1.1.7
      type: app_store
      name: tk-photoshopcc
  #
  # -------------------------------------------------
  # Shell (tank command)
  # -------------------------------------------------
  tk-shell:
    apps:
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchhoudini: '@launch_houdini'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchmotionbuilder: '@launch_motionbuilder'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchphotoshopcc: '@launch_photoshopcc'
      tk-multi-launchsoftimage: '@launch_softimage'
      tk-multi-screeningroom: '@launch_screeningroom'
    location:
      version: v0.5.4
      type: app_store
      name: tk-shell
  #
  # -------------------------------------------------
  # Softimage
  # -------------------------------------------------
  tk-softimage:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    debug_logging: false
    location:
      version: v0.3.2
      type: app_store
      name: tk-softimage
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    template_project:
#
###############################################################################
#
# Framework includes.
#
# Frameworks are libraries that are shared between apps and that contain
# common functionality for building UIs and communicating with Shotgun.
# Frameworks are automatically installed when apps are installed and udpated.
#
frameworks:
  tk-framework-softimageqt_v1.0.1:
    location:
      name: tk-framework-softimageqt
      type: app_store
      version: v1.0.1
