# Shotgun Pipeline Toolkit configuration file
# This file reflects the paths in the pipeline configuration
# entity which is associated with this location

Windows: 'Y:\_PLUGINGS\Shotgun\TheKillTeam'
Darwin: ''
Linux: ''

# End of file.
